server:
  port: 80
eureka:
  client:
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: openFeignOrder80

#设置openFeign客户端超时时间
ribbon:
  #指的是建立链接所用的时间
  ReadTimeout: 5000
  #指的是建立链接后从服务器读取到可用资源的等待时间
  ConnectTimeout: 5000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug
    #feign日志以什么级别监控什么接口
spring:
  application:
    name: cloud-comsumer-service
